# General configuration for the narrative agent

# Environment configuration
environment:
  # Jericho game to use
  game: "zork1"
  # Maximum turns per episode
  max_steps: 100
  # Score threshold to consider success
  score_threshold: 10

# Agent configuration
agents:
  # LLM model to use
  llm_model: "gpt-4"
  # Temperature for generation
  temperature: 0.7
  # Maximum tokens to generate
  max_tokens: 1024

  # Specific parameters for the curriculum agent
  curriculum_agent:
    task_difficulty_scaling: 1.2
    max_failed_tasks_memory: 10

  # Specific parameters for the action agent
  action_agent:
    max_refinement_iterations: 3

  # Specific parameters for the critic agent
  critic_agent:
    strictness: 0.8

# Skill library configuration
skill_library:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  embedding_dim: 384
  top_k_retrievals: 5

# Logging and monitoring
logging:
  level: "INFO"
  save_dir: "logs/"
  save_interval: 10