# Specific configuration for Jericho games

zork1:
  description: "A classic adventure game where you explore an underground world."
  starting_goal: "Explore the world, collect treasures, and survive."
  initial_inventory: ["sword", "lantern"]
  key_locations: ["West of House", "Clearing", "Forest"]
  key_objects: ["leaflet", "mailbox", "sword", "lantern"]
  key_characters: ["troll", "thief"]
  special_commands:
    - "look"
    - "inventory"
    - "examine"
    - "take"
    - "drop"
    - "open"
    - "close"
    - "put"
    - "attack"
    - "eat"
    - "drink"
  progression_milestones:
    - name: "Enter the house"
      score: 10
    - name: "Find the treasure"
      score: 25
    - name: "Defeat the troll"
      score: 40

# Configurations for other Jericho games can be added here
# adventure:
#   description: ...